import { connectMongoDB } from './lib/mongodb';
import { StoryModel } from './models/Story';
import { GenreModel } from './models/Genre';
import { LanguageModel } from './models/Language';
import 'dotenv/config';

const demoAudioUrl = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3';

const storiesData = [
  {
    title: "The Whispering Shadows",
    description: "A chilling tale of a haunted mansion where shadows come alive at midnight. Follow Detective Sarah as she uncovers the dark secrets hidden within the walls of Blackwood Manor.",
    shortDescription: "A chilling tale of a haunted mansion.",
    author: "Eleanor Dark",
    narrator: "Morgan Freeman",
    category: "Horror",
    genres: ["Horror", "Mystery", "Thriller"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 28800,
    planRequired: "premium",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 1250000,
    likes: 45000,
    shares: 12000,
    tags: ["horror", "mystery", "thriller", "audiobook", "bestseller"],
    thumbnail: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "Echoes of the Past",
    description: "When a young musician discovers an old vinyl record in her grandmother's attic, she unwittingly opens a portal to the past. A heartwarming story about love, loss, and the power of music.",
    shortDescription: "A heartwarming story about love and music.",
    author: "James Harmony",
    narrator: "Scarlett Johansson",
    category: "Romance",
    genres: ["Romance", "Drama"],
    languages: ["English", "Hindi"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 21600,
    planRequired: "free",
    featured: false,
    trending: true,
    isNewContent: false,
    views: 980000,
    likes: 32000,
    shares: 8500,
    tags: ["romance", "drama", "music", "heartwarming"],
    thumbnail: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Last Dragon Rider",
    description: "In a world where dragons and humans once lived in harmony, a young orphan discovers she is the last of the Dragon Riders. An epic fantasy adventure that will transport you to another realm.",
    shortDescription: "An epic fantasy adventure.",
    author: "Sarah Dragonborn",
    narrator: "Jeremy Irons",
    category: "Fantasy",
    genres: ["Fantasy", "Adventure", "Sci-Fi"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 39600,
    planRequired: "premium",
    featured: true,
    trending: false,
    isNewContent: true,
    views: 2100000,
    likes: 78000,
    shares: 23000,
    tags: ["fantasy", "adventure", "dragons", "epic"],
    thumbnail: "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1534972195531-d756b9bfa9f2?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "Midnight in Paris",
    description: "A romantic comedy about a young writer who finds himself transported back to 1920s Paris every night at midnight. There, he meets his literary heroes and discovers what truly matters in life.",
    shortDescription: "A romantic comedy through time.",
    author: "Gigi Parisian",
    narrator: "Emma Watson",
    category: "Romance",
    genres: ["Romance", "Comedy"],
    languages: ["English", "French"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 18000,
    planRequired: "standard",
    featured: false,
    trending: true,
    isNewContent: false,
    views: 1560000,
    likes: 67000,
    shares: 18000,
    tags: ["romance", "comedy", "time-travel", "paris"],
    thumbnail: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Quantum Detective",
    description: "Detective Cole can solve crimes by stepping into the quantum realm and witnessing the crime from multiple dimensions. But when a case hits too close to home, he must confront the mysteries of his own past.",
    shortDescription: "Solving crimes across dimensions.",
    author: "Dr. Physics",
    narrator: "Benedict Cumberbatch",
    category: "Sci-Fi",
    genres: ["Sci-Fi", "Mystery", "Thriller"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 32400,
    planRequired: "premium",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 1890000,
    likes: 89000,
    shares: 25000,
    tags: ["sci-fi", "mystery", "thriller", "quantum", "detective"],
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Secret Garden of Dreams",
    description: "A children's fantasy story about a magical garden that only appears at dawn. Follow Lily as she befriends talking animals and learns the true meaning of friendship and courage.",
    shortDescription: "A magical garden adventure for children.",
    author: "Mary Bloom",
    narrator: "Meryl Streep",
    category: "Children",
    genres: ["Fantasy", "Children"],
    languages: ["English", "Spanish"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 14400,
    planRequired: "free",
    featured: false,
    trending: false,
    isNewContent: false,
    views: 4500000,
    likes: 230000,
    shares: 56000,
    tags: ["children", "fantasy", "magic", "friendship"],
    thumbnail: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Lighthouse Keeper's Journal",
    description: "An old lighthouse keeper discovers a mysterious journal washed ashore. As he reads through its pages, he realizes it tells the story of his own life—written by someone who hasn't been born yet.",
    shortDescription: "A mysterious journal from the future.",
    author: "Harbor Wells",
    narrator: "Tom Hanks",
    category: "Mystery",
    genres: ["Mystery", "Sci-Fi", "Drama"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 25200,
    planRequired: "standard",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 3400000,
    likes: 145000,
    shares: 38000,
    tags: ["mystery", "sci-fi", "time-travel", "bestseller"],
    thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "Crimson Moon",
    description: "In a world where vampires and humans coexist, a young vampire falls in love with a human girl. But their forbidden love triggers a chain of events that threatens both worlds.",
    shortDescription: "A forbidden love between worlds.",
    author: "Violet Night",
    narrator: "Anya Taylor-Joy",
    category: "Romance",
    genres: ["Romance", "Fantasy", "Horror"],
    languages: ["English", "French"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 28800,
    planRequired: "premium",
    featured: false,
    trending: true,
    isNewContent: false,
    views: 2780000,
    likes: 156000,
    shares: 42000,
    tags: ["romance", "fantasy", "vampire", "forbidden-love"],
    thumbnail: "https://images.unsplash.com/photo-1497565663456-1c846ce81c7b?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1497565663456-1c846ce81c7b?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1497565663456-1c846ce81c7b?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Time Traveler's Apprentice",
    description: "A young inventor accidentally creates a time machine and is taken under the wing of a mysterious time traveler. Together they must fix the timeline before it unravels completely.",
    shortDescription: "Adventure through time itself.",
    author: "Chrono Smith",
    narrator: "Daniel Radcliffe",
    category: "Sci-Fi",
    genres: ["Sci-Fi", "Adventure", "Comedy"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 36000,
    planRequired: "premium",
    featured: true,
    trending: false,
    isNewContent: true,
    views: 1920000,
    likes: 98000,
    shares: 27000,
    tags: ["sci-fi", "adventure", "time-travel", "comedy"],
    thumbnail: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "Whispers in the Wind",
    description: "A small coastal town is plagued by mysterious whispers carried by the wind. Only a deaf girl can understand what the wind is saying—and it's warning of an ancient evil awakening.",
    shortDescription: "The wind holds ancient secrets.",
    author: "Stormy Blake",
    narrator: "Florence Pugh",
    category: "Horror",
    genres: ["Horror", "Mystery", "Fantasy"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 21600,
    planRequired: "free",
    featured: false,
    trending: true,
    isNewContent: false,
    views: 890000,
    likes: 56000,
    shares: 15000,
    tags: ["horror", "mystery", "supernatural", "small-town"],
    thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Phantom Orchestra",
    description: "A grand concert hall is haunted by a phantom orchestra that only performs at midnight. When a young violinist discovers she can hear them, she's drawn into a musical mystery spanning centuries.",
    shortDescription: "A haunting melody from beyond.",
    author: "Melody Sharp",
    narrator: "Zendaya",
    category: "Mystery",
    genres: ["Mystery", "Fantasy", "Drama"],
    languages: ["English", "German"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 32400,
    planRequired: "standard",
    featured: true,
    trending: false,
    isNewContent: false,
    views: 1650000,
    likes: 112000,
    shares: 29000,
    tags: ["mystery", "fantasy", "music", "ghost", "classical"],
    thumbnail: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Lost City of Zephyr",
    description: "An archaeologist discovers a map leading to a legendary city that exists between dimensions. Her expedition into the unknown will change everything we know about history.",
    shortDescription: "A city between dimensions awaits.",
    author: "Indiana Rivers",
    narrator: "Cate Blanchett",
    category: "Adventure",
    genres: ["Adventure", "Sci-Fi", "Mystery"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 43200,
    planRequired: "premium",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 2340000,
    likes: 134000,
    shares: 36000,
    tags: ["adventure", "sci-fi", "mystery", "archaeology", "lost-city"],
    thumbnail: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Comedy of Errors: Reimagined",
    description: "Shakespeare's classic comedy gets a modern twist in this hilarious audio drama. Two sets of identical twins, mistaken identities, and hilarious chaos ensue in this contemporary adaptation.",
    shortDescription: "Shakespeare meets modern comedy.",
    author: "Will Shakes",
    narrator: "Ryan Reynolds",
    category: "Comedy",
    genres: ["Comedy", "Drama"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 14400,
    planRequired: "free",
    featured: false,
    trending: false,
    isNewContent: false,
    views: 780000,
    likes: 89000,
    shares: 34000,
    tags: ["comedy", "drama", "shakespeare", "classic", "adaptation"],
    thumbnail: "https://images.unsplash.com/photo-1517604931442-710e8ed8a2ab?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1517604931442-710e8ed8a2ab?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1517604931442-710e8ed8a2ab?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Last Symphony",
    description: "A deaf composer creates his magnum opus using vibrations and colors. When a music producer discovers his work, she's determined to share it with the world—even if he can't hear it himself.",
    shortDescription: "Music beyond sound.",
    author: "Harmony Keys",
    narrator: "Riz Ahmed",
    category: "Drama",
    genres: ["Drama", "Music", "Inspirational"],
    languages: ["English", "Hindi"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 28800,
    planRequired: "standard",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 3100000,
    likes: 178000,
    shares: 45000,
    tags: ["drama", "music", "inspirational", "deaf", "bestseller"],
    thumbnail: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "The Enchanted Library",
    description: "A librarian discovers that the books in her library come to life at night. When a villainous character escapes from a fantasy novel, she must team up with a rogue pirate to save the library.",
    shortDescription: "Books come alive at midnight.",
    author: "Page Turner",
    narrator: "Kate Winslet",
    category: "Fantasy",
    genres: ["Fantasy", "Comedy", "Adventure"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 25200,
    planRequired: "free",
    featured: false,
    trending: false,
    isNewContent: false,
    views: 1890000,
    likes: 145000,
    shares: 38000,
    tags: ["fantasy", "comedy", "adventure", "library", "magic"],
    thumbnail: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&h=900&fit=crop&q=80",
  },
  {
    title: "Shadows of the Empire",
    description: "In a galaxy far, far away, a rogue smuggler and a former Imperial officer team up to rescue a kidnapped prince. But their mission reveals a conspiracy that threatens the entire galaxy.",
    shortDescription: "A space opera adventure.",
    author: "Nova Star",
    narrator: "Liam Neeson",
    category: "Sci-Fi",
    genres: ["Sci-Fi", "Adventure", "Action"],
    languages: ["English"],
    status: "published",
    audioUrl: demoAudioUrl,
    duration: 43200,
    planRequired: "premium",
    featured: true,
    trending: true,
    isNewContent: true,
    views: 5600000,
    likes: 289000,
    shares: 72000,
    tags: ["sci-fi", "space", "adventure", "action", "epic"],
    thumbnail: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop&q=80",
    bannerImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200&h=600&fit=crop&q=80",
    coverImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600&h=900&fit=crop&q=80",
  },
];

async function seedStories() {
  try {
    console.log('Connecting to database...');
    await connectMongoDB();

    const dbGenres = await GenreModel.find().lean();
    const genreMap = new Map(dbGenres.map(g => [g.name.toLowerCase(), g._id]));

    const dbLanguages = await LanguageModel.find().lean();
    const languageMap = new Map(dbLanguages.map(l => [l.name.toLowerCase(), l._id]));

    const getGenreIds = (genres: string[]) => genres.map(g => genreMap.get(g.toLowerCase())).filter(Boolean);
    const getLanguageIds = (langs: string[]) => langs.map(l => languageMap.get(l.toLowerCase())).filter(Boolean);

    console.log('Seeding 12 Stories...');
    for (const story of storiesData) {
      const gIds = getGenreIds(story.genres);
      const lIds = getLanguageIds(story.languages);

      await StoryModel.create({
        title: story.title,
        description: story.description,
        shortDescription: story.shortDescription,
        author: story.author,
        narrator: story.narrator,
        category: story.category,
        genres: gIds,
        languages: lIds,
        status: story.status as any,
        audioUrl: story.audioUrl,
        duration: story.duration,
        planRequired: story.planRequired as any,
        featured: story.featured,
        trending: story.trending,
        isNewContent: story.isNewContent,
        views: story.views,
        likes: story.likes,
        shares: story.shares,
        tags: story.tags,
        thumbnail: story.thumbnail,
        bannerImage: story.bannerImage,
        coverImage: story.coverImage,
        rating: 'TV-14',
        ageRating: 14,
      });
    }

    console.log(`All ${storiesData.length} stories seeded successfully!`);
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
}

seedStories();
